//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using CsvHelper.Configuration.Attributes;
    using System;
    using System.Collections.Generic;

    public partial class Movy
    {
        [Name(names: "id")]
        public string ID { get; set; }
        [Name(names: "genres")]
        public string Genres { get; set; }
        [Name(names: "original_language")]
        public string Original_Language { get; set; }
        [Name(names: "budget")]
        public Nullable<decimal> Budget { get; set; }
        [Name(names: "overview")]
        public string Overview { get; set; }
        [Name(names: "popularity")]
        public Nullable<decimal> Popularity { get; set; }
        [Name(names: "production_companies")]
        public string Production_Companies { get; set; }
        [Name(names: "release_date")]
        public System.DateTime Release_date { get; set; }
        [Name(names: "revenue")]
        public Nullable<decimal> Revenue { get; set; }
        [Name(names: "runtime")]
        public Nullable<int> Runtime { get; set; }
        [Name(names: "tagline")]
        public string Tagline { get; set; }
        [Name(names: "title")]
        public string Title { get; set; }
        [Name(names: "vote_average")]
        public Nullable<decimal> Vote_Average { get; set; }
        [Name(names: "vote_count")]
        public Nullable<int> Vote_Count { get; set; }
    }
}
